/**
 * Generated by Pocostick at {{now}}
 */
var POCOSTICK_DEFAULT_NAMESPACE;
(function (POCOSTICK_DEFAULT_NAMESPACE) {
    var POCOSTICK_CLASS_NAME = (function () {
        function POCOSTICK_CLASS_NAME() {
        }
        return POCOSTICK_CLASS_NAME;
    }());
})(POCOSTICK_DEFAULT_NAMESPACE || (POCOSTICK_DEFAULT_NAMESPACE = {}));
//# sourceMappingURL=poco.js.map